gui:
  showIcons: true
  nerdFontsVersion: "2"
  animateExplosion: true
customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit"
    output: terminal
